### ISSUE TITLE
Thank you!

### ISSUE THREAD

**Issue by jared-mackey** [Emoun/duplicate#16]
Just wanted to drop a big thank you for this crate! It saved me from some real nasty stuff. <3

**Comment by Emoun** [comment]
@jared-mackey Thanks for reaching out and you are very welcome, I'm glad it can help you. If your code is open-source or available somewhere, I'd love to have a look. I'm interested in seeing exactly how people make use of it.

**Comment by lokegustafsson** [comment]
I want to do the same - thank you so much for this crate! :heart:

**Comment by Emoun** [comment]
@lokegustafsson You are very welcome, and thanks for reaching out.

I'm glad you like the documentation, it a necessary part of a crate, but a real pain to make. Regarding the download number, I guess I'm just not the best salesman, but if you like, share and subscribe that would really help out this channel 😄
