### ISSUE TITLE
Upgrade heck to v0.3.3 or higher

### ISSUE THREAD

**Issue by harshitpatel96** [Emoun/duplicate#46]
Hey guys, I was wondering when would be next release for this package and if you are going to upgrade heck to v0.3.3 or more. As of now sqlx-macros Crate has a dependency of heck v0.3.3 or more and Duplicate crate requires v0.3.2 which creates conflicts.

**Comment by Emoun** [comment]
@harshitpatel96 yes, a new release is in the works and will be released soon...ish. I will need to find some time to put the finishing touches on it. Might get it out this weekend.

It will include a change to the MSRV which should alleviate version conflicts like yours (#44) and probably update to `heck` v0.4 (which shouldn't have a conflict with v0.3.3).
In the meantime, the `heck` dependency is only used by the `module_disambiguation` feature, so if you turn that off you should be able to compile (see #42).

Please note that the next release will include breaking changes. You can currently see them in the changelog.

**Comment by Emoun** [comment]
@harshitpatel96 New release is out. I hope it solves your issues.
