### ISSUE TITLE
duplicate! as a macro-by-example

### ISSUE THREAD

**Issue by Rimpampa** [Emoun/duplicate#50]
# Introduction

In the last days I made this repo https://github.com/Rimpampa/variants which I later found out it does the same thing as this crate but instead of using a procedural macro it uses a macro-by-example (or declarative macro).

Now instead of making a new crate I was wondering if there was any interest in adding this version of the macro to this crate.

# Differences

There are some differences in the syntax, to give an example here is the examples in the docs made with my macro:
```rust
// 1st example
variants!([$] int_type | max_value: u8 | 255, u16 | 65_535, u32 | 4_294_967_295 => {
    impl IsMax for $int_type {
        fn is_max(&self) -> bool {
            *self == $max_value
        }
    }
});

// 2nd example
impl<T> VecWrap<T> {
    variants!([$] method: get, get_mut => {
        pub fn $method<'a>(
            self: select!(get: {&'a Self}, get_mut: {&'a mut Self}),
            idx: usize,
        ) -> Option<select!(get: {&'a T}, get_mut: {&'a mut T}> {
            self.0.$method(idx)
        }
    });
}
```
The main difference is the use of `$var` syntax for substitution instead of directly using the declared identifier and the usage of the `select!` macro.
Naturally it's not as clean as using a procedural macro and it currently doesn't support nested invocation but by making the syntax similar to the one used by your macro, it could be possible to make it more _flexible_.

## New Look

Using your syntax and adding nesting, the 2nd and 3rd examples could be written like this:
```rust
// 2nd example
impl<T> VecWrap<T> {
    variants!(
        [$] [method] [ref];
        [get] [&'a];
        [get_mut] [&'a mut];
        {
            pub fn $method<'a>(self: $ref Self, idx: usize) -> Option<$ref T> {
                self.0.$method(idx)
            }
        }
    );
}

// 3rd example
variants!(
    [d:$] [types] [impl];
    [[u8]; [u16]; [u32]] [false];
    [[i8]; [i16]; [i32]] [*self < 0];
    {
        variants!([$d] [type]; $types; {
            impl IsNegative for $d type {
                fn is_negative(&self) -> bool {
                    $impl
                }
            }
        });
    }
);
```

# That's it

This is my proposal, I don't have a strong point as to why this should be included so I understand if you don't find this feature useful, but if there is an interest in adding this to the crate, let me know your opinions about it and I'll be willing to work on this to make it suitable for this crate.

**Comment by Emoun** [comment]
@Rimpampa thanks for the proposal, it is always interesting to see how other people tackle this problem.

Some clarification questions:

If I understand `select!` right, it checks whether it is expanding for `get` or `get_mut` (in example 2) and output `&'a Self` or `&'a mut Self` respectively, correct?
But, how does it know which substitution variable (you only have `method` in this example, but say there was another one like in the first example) to use for the selection?

You say this macro could be more flexible. Can you give an example of what functionality it could provide that the existing macros can't?

General comments:

`duplicate` was actually [originally implemented as a declarative macro](https://github.com/Emoun/graphene/blob/4d6502aa1e62bce4768ce28f16f49e18991715e1/tests/all_tests.rs#L41). 
In my personal experience, maintaining and adding features to complex declarative macros is more difficult than procedural macros. Therefore, I would be hesitant to add such a macro to this crates without good reason. 
Don't take this as a blanket rejection though.

Another issue with declarative macros as a library is error reporting. If the user uses the wrong syntax, they will get a cryptic error about a token not having any rule. With procedural macros, we can provide custom error reporting helping the user find their error. We even have a feature named `pretty-errors` specifically for this (though not fully implemented yet, help is welcome!).

**Comment by Rimpampa** [comment]
Thanks for considering the proposal @Emoun, I'll answer your questions:

> If I understand select! right, it checks whether it is expanding for get or get_mut (in example 2) and output &'a Self or &'a mut Self respectively, correct?

Yes, this is what it does, it also supports using | for matching more _variants_ at once (that's how I called them)

> But, how does it know which substitution variable (you only have method in this example, but say there was another one like in the first example) to use for the selection?

The selection considers the substitution variables as _aliases_, it's probably better shown with an example:
```rust
variants!([$] a | b: c | d => { select!(c | d: ()); })
```
The `select!` will always match, because `c` and `d` refer to the same "_substitution variable group_".

BTW: `select!` was a nice feature that I thought at first but everything it does can be probably be done with the substitution variables.

> You say this macro could be more flexible

I probably could have written that part better, but I meant that using the same syntax as `duplicate!` would make my macro more flexible (relative to itself not to `duplicate!`).

There is also another fact regarding this part: I actually started working on making the syntax similar to `duplicate!` but one thing I didn't consider while making the example yesterday is that by allowing arbitrary tokens as substitution values, the substitution variables have to be in the form `$($<var>:tt)*` which means that the examples I made yesterday would look like this:
```rust
// 2nd example
impl<T> VecWrap<T> {
    variants!(
        [$] [method] [ref];
        [get] [&'a];
        [get_mut] [&'a mut];
        {
            pub fn $($method)*<'a>(self: $($ref)* Self, idx: usize) -> Option<$($ref)* T> {
                self.0.$($method)*(idx)
            }
        }
    );
}

// 3rd example
variants!(
    [d:$] [types] [impl];
    [[u8]; [u16]; [u32]] [false];
    [[i8]; [i16]; [i32]] [*self < 0];
    {
        variants!([$d] [type]; $($types)*; {
            impl IsNegative for $d ($d type)* {
                fn is_negative(&self) -> bool {
                    $($impl)*
                }
            }
        });
    }
);
```
Which is not that pretty, and kind of confusing.

> In my personal experience, maintaining and adding features to complex declarative macros is more difficult than procedural macros. 

You probably know better then me and I'm aware of the problem as writing the macro was not that straightforward.

> Another issue with declarative macros as a library is error reporting

That's right, in the current implementation of `variants!` I tried to make common errors as clear as possible, which turned out to be ok, but, in the syntax experiment mentioned above, errors started to become worse.

## Conclusions

There are a lot of downsides by using a macro-by-example, the only thing I can think of that would get better is the compile times, which can't be said for sure as there aren't any benchmarks that prove it.

When I'll have time I'll publish a branch on my repo with a version of the macro that uses the same syntax as `duplicate!`.
In the meanwhile let me know what you think about this, if there is anything that can be done even if I understand that it's probably better to leave it outside this crate.

Regardless, I'll try to take a look at the `pretty-errors` feature, thanks again for your time and interest

**Comment by Emoun** [comment]
@Rimpampa thank you for your time and interest too.

Regarding compile that is actually something I've though about and would like to look into one day, but there is so much else to do first. If you do some benchmarking I'll be happy to see the results.

For now, I don't see a reason to add `variants` to this crate, so I'm going to close this issue. But best of luck with your further work on `variants` and if you find something interesting I'll be happy to hear about it.

Also, if you're interested in contributing to this crate, feel free to take a look at the open issues and comment there if you want to work on something. I'll be happy to help get you started.
