### ISSUE TITLE
How to use with conditional compilation (cfg-macro)?

### ISSUE THREAD

**Issue by DerZade** [Emoun/duplicate#56]
I use the `duplicate` macro to generate a sync and a async version of a function. I would like to include the async version only if the feature `async` is enabled. Is there any way to achieve that?

The following code, does not work. I guess this is because the `cfg` macro has a "higher" priority as the `duplicate_item` macro and therefore it just says _"code is inactive due to #[cfg] directives: cfg_filter is disabled"_
```rs
#[duplicate_item(
    fn_name             cfg_filter        async;
    [my_function]       [all()]           [];
    [my_function_async] [feature="async"] [async];
)]
#[cfg(cfg_filter)]
async fn fn_name() {
    todo!()
}
```

Thanks a lot in advance!

**Comment by DerZade** [comment]
After playing around with it a bit more, I found a solution, but it is very verbose:

```rs
#[cfg_attr(feature = "async", 
    duplicate_item(
        fn_name             async;
        [my_function]       [];
        [my_function_async] [async];
    )
)]
#[cfg_attr(not(feature = "async"), 
    duplicate_item(
        fn_name             async;
        [my_function]       [];
    )
)]
async fn fn_name() {
    todo!()
}
```

Is there any better way?

**Comment by Emoun** [comment]
I tried your first example, that you said didn't work, and it seems to work for me when using one my feautures (pretty_errors):

With the feature disabled the expansion resulted in:

```rust
#[cfg(all())]
fn my_function() {
    ::core::panicking::panic("not yet implemented")
}
```

With the feature enabled result was:
```rust
#[cfg(all())]
fn my_function() {
    ::core::panicking::panic("not yet implemented")
}
#[cfg(feature = "pretty_errors")]
async fn my_function_async() {
    ::core::panicking::panic("not yet implemented")
}
```

However, I then tried to make another feature called "async", and this didn't work. I also tried a few more names, and they didn't work either. For some reason, only two of my feature names would work. This is extremely weird but also not a problem with `duplicate` but with `#[cfg(feature = "...")]` not working for some features. 
I confirmed this by testing without using `duplicate` at all, and seeing that `#[cfg(feature = "...")]` would always be false for some features but not others.

I don't have time to look into this any more today, but if you can replicate what I've done perhaps this is a bug in the compiler and we should open an issue in  rust-lang/rust.

**Comment by DerZade** [comment]
> I don't have time to look into this any more today, but if you can replicate what I've done perhaps this is a bug in the compiler and we should open an issue in rust-lang/rust.

The following is my example from the OP with your feature (pretty_errors). Did I understand correctly that that worked for you, because it does not work for me 😅 
```rs

#[duplicate_item(
    fn_name             cfg_filter                async;
    [my_function]       [all()]                   [];
    [my_function_async] [feature="pretty_errors"] [async];
)]
#[cfg(cfg_filter)]
async fn fn_name() {
    todo!()
}

fn shit() {
    my_function()
}
```

**Comment by Emoun** [comment]
Trying again, I got the following to work (regardless of feature name, so lets ignore that part of my last comment):

```rust
#[duplicate::duplicate_item(
    fn_name             cfg_filter                async;
    [my_function]       [cfg(all())]                   [];
    [my_function_async] [cfg(feature="async")] [async];
)]
#[cfg_filter]
async fn fn_name() {
    todo!()
}

fn shit() {
    my_function()
}
```
The key was moving `cfg(` into the substitution for both cases. Let me know if this works for you too.

Having to do this seems to me as a compiler error. If you look at the [rust reference](https://doc.rust-lang.org/reference/attributes.html#meta-item-attribute-syntax), their example shows that attributes should be expanded in descending order, which would imply `duplicate` should be able do what you originally tried. I'm going to open an issue about this in rustc and we'll see what they say

**Comment by Emoun** [comment]
@DerZade this issue seems to be known (rust-lang/rust#83331) but will probably not be fixed in the immediate future, so I would stick to moving the `cfg(` part into `duplicate_item` as mentioned earlier.

**Comment by DerZade** [comment]
Thank you very much! Moving the `cfg(` into the duplicate worked flawlessly 🙃
