### ISSUE TITLE
Replace proc-macro-error with proc-macro2-diagnostics

### ISSUE THREAD

**Issue by bash** [Emoun/duplicate#61]
`proc-macro-error` which is used for pretty errors [seems to be unmaintained](https://gitlab.com/CreepySkeleton/proc-macro-error/-/issues/20) and also [still depends on Syn 1.x](https://gitlab.com/CreepySkeleton/proc-macro-error/-/merge_requests).

The latter is my main driver for opening this issue as I'm [working on cutting down on duplicate dependencies](https://github.com/janhohenheim/foxtrot/pull/311) in @janhohenheim's Bevy game template [Foxtrot](https://github.com/janhohenheim/foxtrot). His template is quite representative of the kinds of dependencies that you'll find in Bevy games.

I propose replacing it with [proc-macro2-diagnostics](https://github.com/SergioBenitez/proc-macro2-diagnostics). Doing so is quite easy (I have a PR ready).

**Comment by Emoun** [comment]
Hi @bash, 
Thank you very much for this issue and PR. I will take a look at this as soon as I can, but it might take some days.
Is this time-sensitive for you? Especially regarding getting a new version released? 
I was planning on the next release being v2.0 with some more features, but could change my feature plans if needed.

**Comment by bash** [comment]
Hi @Emoun 

We're currently using a `[patch]` section in Foxtrot to depend on my fork of `duplicate` so this is definitely not time-sensitive ^^

If it's not too much extra work I would appreciate a new 1.x release though so that we don't have to wait for our dependencies to upgrade to 2.0.

**Comment by Emoun** [comment]
Regarding a another v1 release, I don't that's possible without breaking the MSRV policy, as syn v2 does not run on rust 1.42.
I've had this problem before. Moving to a duplicate v2 will allow me to update such dependencies.

Even though I'm planning a v2, the breaking changes should not actually require much change of user code (hopefully no change for most code). So if you're anyway sending PRs to your dependencies, making them change to v2 shouldn't be too difficult.

I'll think about this some more, but I cannot promise another v1 release.

**Comment by bash** [comment]
> Regarding a another v1 release, I don't that's possible without breaking the MSRV policy, as syn v2 does not run on rust 1.42.

Ah, right I totally forgot about that. Good point

**Comment by Emoun** [comment]
I have decided to accept moving over to proc-macro2-diagnostics.

Missing work:

- [ ] Accept PR
- [ ] Update Changelog

**Comment by Emoun** [comment]
@bash Just wanted to update you that `duplicate` v2.0.0 is now live containing the changes in this issue.

**Comment by bash** [comment]
Thanks! ❤️
